apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: workercontagem-scaledobject
spec:
  scaleTargetRef:
    name: workercontagem
  pollingInterval: 15
  cooldownPeriod:  30
  minReplicaCount: 0
  maxReplicaCount: 10
  triggers:
  - type: azure-eventhub
    metadata:
      connectionFromEnv: AzureEventHubs__EventHubsConnectionString
      storageConnectionFromEnv: AzureEventHubs__BlobStorageConnectionString
      consumerGroup: workerk8s
      unprocessedEventThreshold: '10'
      blobContainer: hubcontagem
      checkpointStrategy: blobMetadata